### ISSUE TITLE
ValueError: Action dimension mismatch

### ISSUE THREAD

**Issue by wangjunyi9999** [RikishK/Reacher-v2_Reinforcement_Learning#1]
Hi, bro, I met this ValueError when I run the Reacher-V2 repo main.py. Did you configure other mujoco relating files? Or what else should I do firstly except basic gym and mujoco environment building? 

Hope to see your reply~

**Comment by RikishK** [comment]
Hi,
There were flags/ Environment variables that needed to be setup. I recommend launching in pycharm as you can just set flags in the run options.

These need to be setup:
LD_LIBRARY_PATH, MUJOCO_PY_PATH, MUJOCO_PY_MJKEY_PATH


  Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: wangjunyi9999 ***@***.***>
Sent: Thursday, August 4, 2022 6:13:05 PM
To: RikishK/Reacher-v2_Reinforcement_Learning ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [RikishK/Reacher-v2_Reinforcement_Learning] ValueError: Action dimension mismatch (Issue #1)


Hi, bro, I met this ValueError when I run the Reacher-V2 repo main.py. Did you configure other mujoco relating files? Or what else should I do firstly except basic gym and mujoco environment building?

Hope to see your reply~

**Comment by wangjunyi9999** [comment]
@RikishK  Hi, thanks for your reply.  I think I have already  configured the environment because the error seems no relation with the environment virable, it could find the mujoco files in my "GYM library".  I am just curious why the action dimension mismatch with the default  : )

The error belows:
`/home/jy/anaconda3/envs/robotarm/lib/python3.8/site-packages/gym/envs/registration.py:592: UserWarning: WARN: The environment Reacher-v2 is out of date. You should consider upgrading to version `v5`.
  logger.warn(
/home/jy/anaconda3/envs/robotarm/lib/python3.8/site-packages/gym/envs/mujoco/mujoco_env.py:237: UserWarning: WARN: This version of the mujoco environments depends on the mujoco-py bindings, which are no longer maintained and may stop working. Please upgrade to the v4 versions of the environments (which depend on the mujoco python bindings instead), unless you are trying to precisely replicate previous works).
  logger.warn(
/home/jy/anaconda3/envs/robotarm/lib/python3.8/site-packages/gym/core.py:329: DeprecationWarning: WARN: Initializing wrapper in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
/home/jy/anaconda3/envs/robotarm/lib/python3.8/site-packages/gym/wrappers/step_api_compatibility.py:39: DeprecationWarning: WARN: Initializing environment in old step API which returns one bool instead of two. It is recommended to set `new_step_api=True` to use new step API. This will be the default behaviour in future.
  deprecation(
NEW TRAIN:  1
[-0.70269059  0.19414907] -1.0 1.0
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    m, r = system.train_agent(tr_epsds, epsd_steps)
  File "/home/jy/junyi/Reacher-v2_Reinforcement_Learning/system.py", line 267, in train_agent
    event = self.interaction(learn=False)
  File "/home/jy/junyi/Reacher-v2_Reinforcement_Learning/system.py", line 220, in interaction
    s, reward, d, _ = self.env.step(scale_action(action, self.min_action, self.max_action))
  File "/home/jy/anaconda3/envs/robotarm/lib/python3.8/site-packages/gym/envs/mujoco/reacher.py", line 32, in step
    self.do_simulation(a, self.frame_skip)
  File "/home/jy/anaconda3/envs/robotarm/lib/python3.8/site-packages/gym/envs/mujoco/mujoco_env.py", line 176, in do_simulation
    raise ValueError("Action dimension mismatch")
ValueError: Action dimension mismatch
`
Also, I have checked the printed action result, it is `[-0.70269059  0.19414907]` ,nothing wrong  : (

**Comment by wangjunyi9999** [comment]
Ok, I solve it now. The error reason is data structure. Actually, we should add `np.array()` for action, and for the tensor of action, we also need transfer it to numpy format. 

Hope it would be a good tip for others who meet the similar issue.
